### ISSUE TITLE
structural changes: uniy sorting_key and observable

### ISSUE THREAD

**Issue by jonaspleyer** [jonaspleyer/Model-Design-Fischer-Information-Matrix#2]
The file `pool_model.py` has the function `sorting_key(x)` and in the file `src/solving.py`, we have to supply the observable which is often simply given by one of the predefined functions `convert_S_matrix_to...`.
Additionally the function `calculate_Fischer_observable` in file `src/solving.py` needs to be adjusted such that all arguments `times, Q_arr, P, Const, S` are given to the `observable` function.

The file `src/optimization.py` uses this `sorting_key` function which is pointless since we always want to sort by the observable itself (which is simply a number).

**Comment by polinagaindrik** [comment]
Does it mean that we want in the functions `convert_S_matrix_to...` straightaway to divide the determinant (or other observable) by effort? And save already this new value in `fischer_results`, right?

**Comment by jonaspleyer** [comment]
The goal is to get rid of the `sorting_key` and only use ˋobservableˋ. We will provide some functions such as calculating the Fischer determinant or sum of Eigenvalues. Custom observable are to be defined in the corresponding model files.

In general: everything in `src/...` is model-agnostic!

**Comment by jonaspleyer** [comment]
Since commit 7b47808078238febd21c6b146a41c2f599602342, sorting key is now a model-specific (to pool_model.py) quantity and not part of the abstraction.
