### ISSUE TITLE
Add uncertainty (variance) of the measurements in Fisher information matrix calulation

### ISSUE THREAD

**Issue by polinagaindrik** [jonaspleyer/Model-Design-Fischer-Information-Matrix#8]
Calculate the Fisher information matrix as F =S^T Q S, where Q is the inverse of the covariance matrix  (\propto 1 / sigma^2).

Now it calculates just F = S^T S.

**Comment by jonaspleyer** [comment]
we should make this an optional argument. If it is not supplied just use a unit-matrix.

**Comment by jonaspleyer** [comment]
Was introduced by commit b2e914742abf26f5ea20e7437fbbe81a1df595b0.
