### ISSUE TITLE
cleanup commit b2e914742abf26f5ea20e7437fbbe81a1df595b0

### ISSUE THREAD

**Issue by jonaspleyer** [jonaspleyer/Model-Design-Fischer-Information-Matrix#9]
Commit b2e914742abf26f5ea20e7437fbbe81a1df595b0 introduced the covariance matrix to the calculation.
Some parts of the changes should be rethough/dropped:
1. [pool_model_make_plots.py](https://github.com/Spatial-Systems-Biology-Freiburg/Model-Design-Fischer-Information-Matrix/commit/b2e914742abf26f5ea20e7437fbbe81a1df595b0#diff-6bc300ddf9fdf873409640e8434f3864d81bcd15c468bf01e84f6e04da7bfc75) had inserted some more comments. This should be dropped
2. [src/solving.py](https://github.com/Spatial-Systems-Biology-Freiburg/Model-Design-Fischer-Information-Matrix/commit/b2e914742abf26f5ea20e7437fbbe81a1df595b0#diff-aabf6634305e4f77aea3f8c4e5a2c0598dc06f669176e74eca5f606539491532) now calculates the relative error with 25% which is not desired since it can not be adjusted from outside in any form. Also: how could we possibly supply a absolute error or avoid computing the covariance matrix. I can see that relative error calculation is desired but the current implementation should be generalized.
3. [pool_model.py](https://github.com/Spatial-Systems-Biology-Freiburg/Model-Design-Fischer-Information-Matrix/commit/b2e914742abf26f5ea20e7437fbbe81a1df595b0#diff-b8aa1fc6781906ae6de43f601c9caf1808a345ac8cc1755a323105f06fb08da3) got an empty line commited. Drop that change.

**Comment by polinagaindrik** [comment]
1. Commit a5a944810870be0dd60cecf2b5d7d4a1754ca360
2. Commit 1bb69bf899c1afa962855ea94: Add choice of covariance matrix method
